language: node_js
node_js:
- 14
- 12
- 10
cache:
  yarn: true
  directories:
  - node_modules
install:
- yarn
script:
- yarn test
- yarn cov
deploy:
  provider: npm
  email: rojand94@gmail.com
  api_key:
    secure: C9AecHX+uNp3ILSSdnjfDCCxU6ZCxVYZpq8aksQRSBeAJV/tHr043S5pA7fDnS98fkWOxRBImjbNTNpUPihLKPZYjQznfraua4JK4FnkMqP6QuoQ9peYbE+38I6UUB41zGI3P20bsIJslegAaQFlw1drFlV4qMe61tQ/GfgB60qPKsslOObIzQy+12qmsWLL62Qa3YQC7Wy04JMm0Nvi4AbCKz89aXua+/7a1ow/rjcGljDIX9PDXDm+dO1HVIWz2Y/lgBEueq7E2GDElQAd5hiHEN3rQpNThMCvmXFedV6KwUJQTT9N2lpzCTU/FG3kR8GFq0VonZpvVyNrjp74AZY2zZJ4f3CLWg/3sHkSpeizVRQfVpqhINfiSC43hfcI/i9RnfF2y7HgeZ5ZnPzzwfrJLVj2VcjXJPncrBUmEb9ZtN6HnIa4qWVojvAp3oeQZuIqC0wkmEnzUnqvS42neVihnhYs6JqBEiFlQzdxp+rO/3nVi3LdvSnPs2t90pj6jmbsjYkr2Vvyx0X6nTadnxVksxL8iwHIyOsTGBvr7KftiwoBfIr2+0TKxc9WoNRYwf5F2wmVME3NPsXkdSzO1owLdvWNVqsmpxAiztIfHJVEgdihTEE6bzkkep8n3Bo1ROMGmLw3uo4x0fSi7pCsml0r28ZloNiNxXLZmXXmCZA=
  on:
    tags: true
    repo: rojanDinc/rop-monads
  skip_cleanup: 'true'
